require("plugins")
require("settings")
require("statusline")
require("keymappings")
require("telescopes")
require("lsp_config")
require("formatter")
require("linters")
require("nice")
vim.cmd([[colorscheme catppuccin-mocha]])
-- vim.cmd([[hi Normal guibg=NONE ctermbg=NONE]])
